CREATE TABLE address_book(
    no INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(45) NOT NULL,
    tel VARCHAR(45) NOT NULL,
    address VARCHAR(100) NOT NULL,
    reg_date TIMESTAMP NOT NULL DEFAULT NOW(),
    upd_date TIMESTAMP NOT NULL DEFAULT NOW()
)COMMENT = '주소록';
